### ISSUE TITLE
Give examples for binary data formats - or destroy!

### ISSUE THREAD

**Issue by smaria** [WRSC/rules#5]
Is it possible to give examples for the binary formats? Are there any teams actually using this format - with data storage getting cheaper and cheaper I suspect this is deprecated...

**Comment by takluyver** [comment]
It's trickier to give examples because binary is not very human readable. On this one I think it is reasonable to ask on the mailing list what teams are already logging. I would guess that most are either using the text format, or can easily transform their logs into the text format.

**Comment by smaria** [comment]
ah well, we will leave it in as is for now
